#
# Makefile for the Novatek NT36xxx touchscreen driver.
#

# Each configuration option enables a list of files.

obj-$(CONFIG_TOUCHSCREEN_NT36672) += nt36672.o nt36672_fw_update.o nt36672_ext_proc.o nt36672_mp_ctrlram.o
